apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: vote
spec:
  selector:
    matchLabels:
      app: redis-deployment
  template:
    metadata:
      labels:
        app: redis-deployment
    spec:
      containers:
        - name: redis-container
          image: redis:alpine
          volumeMounts:
            - mountPath: /data
              name: redis-data
          ports:
            - containerPort: 6379
      volumes:
        - name: redis-data
          emptyDir: {}
