apiVersion: apps/v1
kind: Deployment
metadata:
  name: ic-deploy-datacenter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ic-datacenter
  template:
    metadata:
      labels:
        app: ic-datacenter
    spec:
      containers:
        - name: ic-main-datacenter
          image: centos:latest
          command:
            - "/bin/bash"
            - "-c"
            - "while true; do cat /ic/ecommerce; sleep 5; done"
          volumeMounts:
            - name: ic-volume-datacenter
              mountPath: /ic
      initContainers:
        - name: ic-msg-datacenter
          image: centos:latest
          command:
            - "/bin/bash"
            - "-c"
            - "echo 'Init Done - Welcome to xFusionCorp Industries' > /ic/ecommerce"
          volumeMounts:
            - name: ic-volume-datacenter
              mountPath: /ic
      volumes:
        - name: ic-volume-datacenter
          emptyDir: {}
