# mount a secret to container and access it.
# secret-devops-pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: secret-devops
  labels:
    name: centos
spec:
  containers:
    - name: secret-container-devops
      image: centos:latest
      command: ["/bin/sh", "-c", "sleep infinity"]
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: secret-volume
          mountPath: /opt/cluster
  volumes:
    - name: secret-volume
      secret:
        secretName: blog

---
# generic-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: blog
type: Opaque
data:
  key: NWVjdXIz
