---
apiVersion: v1
kind: Namespace
metadata:
  name: datacenter

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: time-config
  namespace: datacenter
data:
  TIME_FREQ: "10"

---
apiVersion: v1
kind: Pod
metadata:
  name: time-check
  namespace: datacenter
spec:
  containers:
    - name: time-check
      image: busybox:latest
      command: ["/bin/sh", "-c"]
      args:
        - "while true; do date; sleep $TIME_FREQ; done >> /opt/time/timecheck.log"
      env:
        - name: TIME_FREQ
          valueFrom:
            configMapKeyRef:
              name: time-config
              key: TIME_FREQ
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
        requests:
          cpu: "0.1"
          memory: "64Mi"
      volumeMounts:
        - name: log-volume
          mountPath: /opt/time/
  volumes:
    - name: log-volume
      emptyDir: {}
