apiVersion: v1
kind: Service
metadata:
  name: nautilus-app-service
spec:
  type: NodePort
  selector:
    app: nginx-phpfpm
  ports:
    - protocol: TCP
      port: 8095
      targetPort: 8095
      nodePort: 30012
